// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGdqdqlE7afAatdiGsEe_whMvuRSuRlSw',
    appId: '1:46299159815:web:cddb2c31e60b2aa300f9a2',
    messagingSenderId: '46299159815',
    projectId: 'quiz-crafter',
    authDomain: 'quiz-crafter.firebaseapp.com',
    storageBucket: 'quiz-crafter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiaCBkCmTMw-MLQJZKHJ9AwakgKWmEt4k',
    appId: '1:46299159815:android:ab67c199e00d414500f9a2',
    messagingSenderId: '46299159815',
    projectId: 'quiz-crafter',
    storageBucket: 'quiz-crafter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1sffEXmrkhVvg5dDFT-Wj3WFe2OoKf_0',
    appId: '1:46299159815:ios:c729319d1c21959f00f9a2',
    messagingSenderId: '46299159815',
    projectId: 'quiz-crafter',
    storageBucket: 'quiz-crafter.firebasestorage.app',
    iosBundleId: 'com.example.quizCrafter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1sffEXmrkhVvg5dDFT-Wj3WFe2OoKf_0',
    appId: '1:46299159815:ios:c729319d1c21959f00f9a2',
    messagingSenderId: '46299159815',
    projectId: 'quiz-crafter',
    storageBucket: 'quiz-crafter.firebasestorage.app',
    iosBundleId: 'com.example.quizCrafter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGdqdqlE7afAatdiGsEe_whMvuRSuRlSw',
    appId: '1:46299159815:web:6fad7f2189552f4300f9a2',
    messagingSenderId: '46299159815',
    projectId: 'quiz-crafter',
    authDomain: 'quiz-crafter.firebaseapp.com',
    storageBucket: 'quiz-crafter.firebasestorage.app',
  );
}
